# Application Configuration

# WebRTC configuration
webrtc:
  # WebRTC server settings
  server:
    host: localhost
    port: 8000
    # Additional WebRTC server options...

# Text-to-Speech (TTS) configuration
tts:
  # TTS engine settings
  	TTSmodel: bootycheeks
	Vocodermodel :
    
    # Additional TTS engine options...

# Whisper configuration
whisper:
  # Whisper server settings
  server:
    host: example.com
    port: 8080
    # SSL/TLS configuration...
    # Additional Whisper server options...

# Ollama configuration
ollama:
  # Ollama service settings
  service:
    url: https://api.ollama.com
    # Authentication token or credentials...
    # Additional Ollama service options...

